name: Run Vitest with Bun

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for latest commit
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.6

      - name: Install dependencies
        working-directory: client
        run: bun install

      - name: Run Vitest
        working-directory: client
        run: bun run test:unit -- --run

      - name: Check Code Formatting
        working-directory: server
        run: bun eslint .
